import pptxgen from 'pptxgenjs';

export interface SlideData {
  title: string;
  subtitle?: string;
  bullets?: string[];
  cards?: { title: string; desc: string; iconText?: string }[];
  speakerNotes?: string;
  badge?: string;
  quote?: string;
}

export interface PresentationDeckData {
  title: string;
  subtitle: string;
  topic: string;
  theme?: 'dark' | 'cyan' | 'midnight' | 'light';
  slides: SlideData[];
}

/**
 * Generate and download an authentic Microsoft PowerPoint (.pptx) file
 */
export async function downloadPptxFile(deck: PresentationDeckData, fileName?: string): Promise<void> {
  const pres = new pptxgen();

  // Configure presentation wide 16:9 layout
  pres.layout = 'LAYOUT_16x9';
  pres.author = 'NEXORA by Alakh';
  pres.company = 'NEXORA AI';
  pres.title = deck.title;
  pres.subject = deck.topic;

  const isLight = deck.theme === 'light';
  const bgColor = isLight ? 'F8FAFC' : '0B0F19';
  const cardBg = isLight ? 'FFFFFF' : '151C2C';
  const cardBorder = isLight ? 'CBD5E1' : '2D3748';
  const titleColor = isLight ? '0F172A' : 'F8FAFC';
  const subtitleColor = isLight ? '475569' : '94A3B8';
  const textColor = isLight ? '334155' : 'E2E8F0';
  const accentColor = '0284C7'; // Sky / cyan accent
  const accentColor2 = '6366F1'; // Indigo accent

  deck.slides.forEach((slideData, idx) => {
    const slide = pres.addSlide();
    slide.background = { color: bgColor };

    // Slide number and header brand pill
    slide.addText(`NEXORA BY ALAKH  •  ${deck.topic.slice(0, 45)}`, {
      x: 0.8,
      y: 0.35,
      w: 8.5,
      h: 0.3,
      fontSize: 9,
      fontFace: 'Arial',
      color: subtitleColor,
      bold: true,
    });

    slide.addText(`${idx + 1} / ${deck.slides.length}`, {
      x: 11.5,
      y: 0.35,
      w: 1.0,
      h: 0.3,
      fontSize: 9,
      fontFace: 'Arial',
      color: subtitleColor,
      align: 'right',
    });

    if (idx === 0) {
      // TITLE SLIDE
      if (slideData.badge) {
        slide.addText(slideData.badge.toUpperCase(), {
          x: 1.0,
          y: 1.6,
          w: 4.5,
          h: 0.4,
          fontSize: 10,
          fontFace: 'Arial',
          color: accentColor,
          bold: true,
        });
      }

      slide.addText(slideData.title, {
        x: 1.0,
        y: 2.2,
        w: 11.3,
        h: 1.8,
        fontSize: 32,
        fontFace: 'Arial',
        color: titleColor,
        bold: true,
      });

      if (slideData.subtitle) {
        slide.addText(slideData.subtitle, {
          x: 1.0,
          y: 4.2,
          w: 11.0,
          h: 1.0,
          fontSize: 16,
          fontFace: 'Arial',
          color: subtitleColor,
        });
      }

      // Metadata footer box
      slide.addShape(pres.ShapeType.roundRect, {
        x: 1.0,
        y: 5.6,
        w: 11.3,
        h: 0.8,
        fill: { color: cardBg },
        line: { color: cardBorder, width: 1 },
        rectRadius: 0.1,
      });

      slide.addText(`Generated by NEXORA Unified AI Command Center  •  Author: Alakh Shukla  •  Deck Specification: 16:9 Presentation Format`, {
        x: 1.2,
        y: 5.85,
        w: 10.9,
        h: 0.4,
        fontSize: 10,
        fontFace: 'Arial',
        color: subtitleColor,
      });
    } else {
      // CONTENT SLIDES
      if (slideData.badge) {
        slide.addText(slideData.badge.toUpperCase(), {
          x: 0.8,
          y: 0.75,
          w: 5.0,
          h: 0.3,
          fontSize: 10,
          fontFace: 'Arial',
          color: accentColor,
          bold: true,
        });
      }

      slide.addText(slideData.title, {
        x: 0.8,
        y: 1.1,
        w: 11.5,
        h: 0.8,
        fontSize: 22,
        fontFace: 'Arial',
        color: titleColor,
        bold: true,
      });

      if (slideData.subtitle) {
        slide.addText(slideData.subtitle, {
          x: 0.8,
          y: 1.9,
          w: 11.5,
          h: 0.5,
          fontSize: 13,
          fontFace: 'Arial',
          color: subtitleColor,
        });
      }

      // Render cards or bullets
      if (slideData.cards && slideData.cards.length > 0) {
        const count = Math.min(slideData.cards.length, 3);
        const cardWidth = (11.5 - (count - 1) * 0.35) / count;

        slideData.cards.slice(0, 3).forEach((card, cIdx) => {
          const cardX = 0.8 + cIdx * (cardWidth + 0.35);

          slide.addShape(pres.ShapeType.roundRect, {
            x: cardX,
            y: 2.6,
            w: cardWidth,
            h: 3.8,
            fill: { color: cardBg },
            line: { color: cardBorder, width: 1 },
            rectRadius: 0.15,
          });

          // Card accent top line
          slide.addShape(pres.ShapeType.rect, {
            x: cardX + 0.2,
            y: 2.8,
            w: 0.5,
            h: 0.05,
            fill: { color: cIdx === 0 ? accentColor : cIdx === 1 ? accentColor2 : '10B981' },
          });

          slide.addText(card.title, {
            x: cardX + 0.2,
            y: 3.1,
            w: cardWidth - 0.4,
            h: 0.6,
            fontSize: 14,
            fontFace: 'Arial',
            color: titleColor,
            bold: true,
          });

          slide.addText(card.desc, {
            x: cardX + 0.2,
            y: 3.8,
            w: cardWidth - 0.4,
            h: 2.4,
            fontSize: 11,
            fontFace: 'Arial',
            color: textColor,
            lineSpacing: 16,
          });
        });
      } else if (slideData.bullets && slideData.bullets.length > 0) {
        const bulletTextItems = slideData.bullets.map((b) => ({
          text: b,
          options: {
            bullet: true,
            color: textColor,
            fontSize: 13,
            fontFace: 'Arial',
            lineSpacing: 22,
          },
        }));

        slide.addShape(pres.ShapeType.roundRect, {
          x: 0.8,
          y: 2.5,
          w: 11.5,
          h: 4.1,
          fill: { color: cardBg },
          line: { color: cardBorder, width: 1 },
          rectRadius: 0.15,
        });

        slide.addText(bulletTextItems, {
          x: 1.1,
          y: 2.7,
          w: 10.9,
          h: 3.6,
        });
      }
    }

    // Add speaker notes if provided
    if (slideData.speakerNotes) {
      slide.addNotes(slideData.speakerNotes);
    }
  });

  const safeName = (fileName || deck.title || 'Nexora_Presentation')
    .replace(/[^a-zA-Z0-9_-]/g, '_')
    .slice(0, 40);

  await pres.writeFile({ fileName: `${safeName}.pptx` });
}
