import { ProviderDefinition, TaskMode, PromptTemplate } from '../types';

export const PROVIDERS_REGISTRY: ProviderDefinition[] = [
  {
    id: 'gemini',
    name: 'Google Gemini',
    category: 'model',
    model: 'gemini-2.5-flash',
    badge: 'Fast & Deep Reasoning',
    color: '#38bdf8',
    accentBorder: 'border-sky-500/40',
    bgTint: 'bg-sky-500/10',
    description: '1M+ token context window, multimodality, fast synthesis & Google search grounding.',
    capabilities: {
      chat: true,
      textGeneration: true,
      reasoning: true,
      streaming: true,
      webResearch: true,
      citations: true,
      imageInput: true,
      fileInput: true,
      codeGeneration: true,
    },
    status: 'connected',
    requiresKey: false, // Provided by server-side runtime or BYOK
  },
  {
    id: 'openai',
    name: 'OpenAI ChatGPT',
    category: 'model',
    model: 'gpt-4o',
    badge: 'General & Analytical',
    color: '#10b981',
    accentBorder: 'border-emerald-500/40',
    bgTint: 'bg-emerald-500/10',
    description: 'High-capability analytical reasoning, concise structured JSON, and code synthesis.',
    capabilities: {
      chat: true,
      textGeneration: true,
      reasoning: true,
      streaming: true,
      imageInput: true,
      fileInput: true,
      codeGeneration: true,
    },
    status: 'connected',
    requiresKey: true,
  },
  {
    id: 'claude',
    name: 'Anthropic Claude',
    category: 'model',
    model: 'claude-3-7-sonnet',
    badge: 'Nuanced & Architecture',
    color: '#f97316',
    accentBorder: 'border-amber-500/40',
    bgTint: 'bg-amber-500/10',
    description: 'Exceptional long-form nuance, system design audits, code refactoring, and ethics.',
    capabilities: {
      chat: true,
      textGeneration: true,
      reasoning: true,
      streaming: true,
      imageInput: true,
      fileInput: true,
      codeGeneration: true,
    },
    status: 'connected',
    requiresKey: true,
  },
  {
    id: 'perplexity',
    name: 'Perplexity Sonar',
    category: 'model',
    model: 'sonar-pro-live',
    badge: 'Live Grounded Citations',
    color: '#06b6d4',
    accentBorder: 'border-cyan-500/40',
    bgTint: 'bg-cyan-500/10',
    description: 'Fresh web intelligence engine with authentic domain citations and verified URLs.',
    capabilities: {
      chat: true,
      textGeneration: true,
      webResearch: true,
      citations: true,
      streaming: true,
      fileInput: true,
    },
    status: 'connected',
    requiresKey: true,
  },
  {
    id: 'copilot',
    name: 'Microsoft Copilot',
    category: 'model',
    model: 'copilot-enterprise-m365',
    badge: 'Enterprise Microsoft 365',
    color: '#3b82f6',
    accentBorder: 'border-blue-500/40',
    bgTint: 'bg-blue-500/10',
    description: 'Official Microsoft Graph / Entra ID enterprise tenant connector.',
    capabilities: {
      chat: true,
      textGeneration: true,
      webResearch: true,
      documentGeneration: true,
    },
    status: 'auth_required',
    requiresKey: true,
  },
  {
    id: 'figma',
    name: 'Figma Connector',
    category: 'design',
    model: 'figma-rest-v1',
    badge: 'Design Context & Tokens',
    color: '#a855f7',
    accentBorder: 'border-purple-500/40',
    bgTint: 'bg-purple-500/10',
    description: 'Read-only frame metadata, layout hierarchy, and design tokens for UX/WCAG review.',
    capabilities: {
      designContext: true,
      fileInput: true,
      export: true,
    },
    status: 'connected',
    requiresKey: true,
  },
  {
    id: 'gamma',
    name: 'Gamma Presentation',
    category: 'presentation',
    model: 'gamma-deck-spec-v1',
    badge: 'Structured Slide Outlines',
    color: '#ec4899',
    accentBorder: 'border-pink-500/40',
    bgTint: 'bg-pink-500/10',
    description: 'Transforms multi-model research into formatted 10-slide visual card decks.',
    capabilities: {
      presentationGeneration: true,
      documentGeneration: true,
      export: true,
    },
    status: 'connected',
    requiresKey: false,
  },
];

export const TASK_MODES: TaskMode[] = [
  {
    id: 'ask',
    label: 'Ask',
    iconName: 'HelpCircle',
    description: 'General inquiry with multi-model validation',
    defaultProviders: ['gemini', 'openai'],
  },
  {
    id: 'research',
    label: 'Research',
    iconName: 'Search',
    description: 'Multi-source verified research with citations',
    defaultProviders: ['perplexity', 'gemini', 'claude'],
  },
  {
    id: 'compare',
    label: 'Compare',
    iconName: 'GitCompare',
    description: 'Side-by-side claim and perspective divergence',
    defaultProviders: ['gemini', 'openai', 'claude', 'perplexity'],
  },
  {
    id: 'brainstorm',
    label: 'Brainstorm',
    iconName: 'Lightbulb',
    description: 'Divergent ideation from heterogeneous models',
    defaultProviders: ['gemini', 'openai', 'claude'],
  },
  {
    id: 'write',
    label: 'Write',
    iconName: 'PenTool',
    description: 'High-polish editorial, narrative, or report drafts',
    defaultProviders: ['claude', 'gemini'],
  },
  {
    id: 'analyze',
    label: 'Analyze',
    iconName: 'BarChart2',
    description: 'Deep data, logic, and market trend audit',
    defaultProviders: ['gemini', 'claude'],
  },
  {
    id: 'code',
    label: 'Code',
    iconName: 'Code',
    description: 'Architecture review, refactoring, and debugging',
    defaultProviders: ['claude', 'openai', 'gemini'],
  },
  {
    id: 'design',
    label: 'Design',
    iconName: 'Layout',
    description: 'Figma frame analysis and WCAG accessibility audits',
    defaultProviders: ['figma', 'gemini', 'claude'],
  },
  {
    id: 'presentation',
    label: 'Presentation',
    iconName: 'Tv',
    description: 'Multi-model research mapped to Gamma slide decks',
    defaultProviders: ['gemini', 'claude', 'gamma'],
  },
  {
    id: 'summarize',
    label: 'Summarize',
    iconName: 'FileText',
    description: 'Long-document executive briefs and key takeaway lists',
    defaultProviders: ['gemini', 'claude'],
  },
  {
    id: 'verify',
    label: 'Verify',
    iconName: 'ShieldCheck',
    description: 'Fact-checking statements across independent engines',
    defaultProviders: ['perplexity', 'gemini', 'openai'],
  },
  {
    id: 'synthesize',
    label: 'Synthesize',
    iconName: 'Combine',
    description: 'Combine multiple responses into an actionable master brief',
    defaultProviders: ['gemini', 'openai', 'claude', 'perplexity'],
  },
];

export const PROMPT_LIBRARY_SEED: PromptTemplate[] = [
  {
    id: 'seed-1',
    title: 'EV Market Intelligence & Technology Roadmap in India',
    category: 'Research',
    prompt: 'Research the latest developments in electric vehicles in India and prepare a concise business briefing covering battery localized supply chains, government FAME subsidies, infrastructure bottlenecks, and prime venture opportunities.',
    recommendedProviders: ['gemini', 'openai', 'claude', 'perplexity'],
    tag: 'Automotive & Strategy',
  },
  {
    id: 'seed-2',
    title: 'Distributed Cloud Architecture & Resiliency Audit',
    category: 'Coding',
    prompt: 'Analyze high-throughput event processing pipelines for payment gateways. Compare Kafka vs. RabbitMQ vs. Google Cloud Pub/Sub across latency under 50k RPS, operational overhead, cost scaling, and disaster recovery failover.',
    recommendedProviders: ['claude', 'openai', 'gemini'],
    tag: 'Systems Architecture',
  },
  {
    id: 'seed-3',
    title: 'Executive Pitch Deck: AI Medical Diagnostics',
    category: 'Presentations',
    prompt: 'Create a 10-slide venture pitch deck outline for an enterprise AI diagnostic triage platform. Include problem statement, clinical proof points, market sizing (TAM/SAM/SOM), regulatory FDA/CE clearance path, and financial model.',
    recommendedProviders: ['gemini', 'claude', 'gamma'],
    tag: 'Healthcare & Venture',
  },
  {
    id: 'seed-4',
    title: 'WCAG 2.2 AA Contrast & Design System Accessibility',
    category: 'Design',
    prompt: 'Audit mobile navigation patterns and dark-mode color tokens for accessibility compliance. Identify touch target deficiencies, color contrast failures in low-light environments, and recommend token revisions.',
    recommendedProviders: ['figma', 'gemini', 'claude'],
    tag: 'Product Design',
  },
  {
    id: 'seed-5',
    title: 'Semiconductor Fabrication & Supply Chain Geopolitics',
    category: 'Business',
    prompt: 'Evaluate the current geopolitical dynamics affecting global 3nm and 2nm semiconductor foundry fabrication. Contrast TSMC, Samsung, and Intel Foundry Services strategies through 2028 with verified citations.',
    recommendedProviders: ['perplexity', 'gemini', 'claude'],
    tag: 'Global Geopolitics',
  },
  {
    id: 'seed-6',
    title: 'Government Procurement & Tender Evaluation Framework',
    category: 'Procurement',
    prompt: 'Synthesize standard public procurement guidelines for high-value cloud software acquisitions. Outline RFP scoring rubrics, cybersecurity compliance checkpoints, vendor lock-in mitigation, and price-to-quality ratios.',
    recommendedProviders: ['gemini', 'openai', 'claude'],
    tag: 'GovTech & Policy',
  },
];
